version: 1.0.{build}
configuration: Release
build:
  verbosity: minimal
after_build:
- ps: nuget pack easyreflection\EasyReflection.nuspec -Version $env:appveyor_build_version
after_test:
- ps: nuget pack easyreflection\EasyReflection.nuspec -Version $env:appveyor_build_version
artifacts:
- path: '**/EasyReflection.*.nupkg'
  name: nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 21INObpCbRn0NPnssWsHAy8gO3nlcuRlZIfcE2ONDN8kVll9NO/F73z6W8Txzjqj
  symbol_server: 
  artifact: nupkg